### ISSUE TITLE
Pinmapping improvement request for 4610 (others, too?)

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/HW-Designs#23]
The 4610 pin mapping file could be a little more clear.

1. please add the JP1 and JP3 numbers as a new field (closest to the board, I think)
2. please change the labels that correspond to Arduino Dn numbers to say D0, D1, etc. rather than 0, 1.
3. move the `A0` that's to the left of `14` (which by previous would be `D14`), so its to the right of `14`, above `A1`.
4. make sure the square pads for JP1 and JP3 are shown in the model.
5. add black `PH1` next to 45 on D10 (that's the port on the STM32.
6. change the pink `BOOT0` to be a port pin -- these are really STM32L0 functional pin lablels. Then add a pink BOOT0 under USART1_TX.

Thanks!

**Comment by svelmurugan92** [comment]
@Veeralakshmi92 Please create a pull request
