### ISSUE TITLE
Feature Request: Access to Feather M0's SWD Pads on the Catena 4450 

### ISSUE THREAD

**Issue by forrestfiller** [mcci-catena/HW-Designs#3]
This is a feature request for your next revision:
====

It would be really great if I didn't have to disassemble the **Catena 4450** with a screwdriver to solder tiny wires to Adafruit's Feather debug pads--I know I would have to do this on a stock Feather, and have done so.

It would be helpful to bring the **SWDIO** and **SWCLK** pads up to debug pins on your board--or somewhere else if you're getting too crowded up top. Then, getting my hardware debugger connected would be a snap!

Thanks!

**Comment by svelmurugan92** [comment]
This feature is included in our new stm32 series Catena boards. I think no plan to add in 4450.
Closing this issue
