### ISSUE TITLE
Need square pads on pin 1 (esp on the Feather module connectors)

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/HW-Designs#4]
We're not consistent about this, and it's a consistent headache when using the boards. Please fix as/when practical.

**Comment by svelmurugan92** [comment]
Noted, Will fix it in next built on both (4450 and 4551).

**Comment by terrillmoore** [comment]
also 4460....

**Comment by terrillmoore** [comment]
I think we can close this, we're pretty good these days with the square pads. @svelmurugan92 , do you agree?

**Comment by svelmurugan92** [comment]
@terrillmoore Yes, We can close this.
