### ISSUE TITLE
Request for pointer sheet in kit contents

### ISSUE THREAD

**Issue by terrillmoore** [mcci-catena/HW-Designs#5]
Russ Nelson wrote:

> -  Include a slip of paper in the 4450 package that points to a page that links to the assembly instructions under HW-Designs,
> - This also should include links to the software instructions under https://github.com/mcci-catena/arduino-boards.

**Comment by svelmurugan92** [comment]
We provided the info in the 4450 web page and store page. Also user guide point it. 
We can close this for issue.
