### ISSUE TITLE
Catena-4450-M102-Assembly-Instructions screws

### ISSUE THREAD

**Issue by RussNelson** [mcci-catena/HW-Designs#6]
In the assembly instructions PDF, reference is made to M2.5 screws, spacers, and a bottom board, none of which came in my kit. I tried to buy M2.5 screws and nuts (or spacers) at Lowe's. No such luck. They only went down to M3. Maybe it would be a kindness to include them? Or if not, then include the length of the necessary M2.5 screw and point to an online source to buy them.

**Comment by svelmurugan92** [comment]
Added the DIY Kit assembly document. Previous M102 docs is created for some special purpose requirement.
