### ISSUE TITLE
kicad files for 4460 and 4470 missing

### ISSUE THREAD

**Issue by ransomhall** [mcci-catena/HW-Designs#8]
The title says it all. Terri says there are also assembly instructions somewhere.

**Comment by terrillmoore** [comment]
Yes, we're working on rationalizing all this. Hoping for something this week.

**Comment by terrillmoore** [comment]
@svelmurugan92 - what happened on this?

**Comment by svelmurugan92** [comment]
@terrillmoore As we don't share direct Kicad files, Instead of that, We have released the schematic and PCB fabrication layout drawing for 4460 and 4470.
I think, We can close this issue.
